version: '3.8'

services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://viraj:123456@account_db:5432/viraj?sslmode=disable
    restart: on-failure

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
      - account
      - catalog
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: postgres://viraj:123456@order_db:5432/viraj?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8081
      CATALOG_SERVICE_URL: catalog:8082
    restart: on-failure

    inventory:
      build:
        context: .
        dockerfile: ./inventory/app.dockerfile
      depends_on:
        - inventory_db
      ports:
        - "8084:8084"
      environment:
        REDIS_URL: redis://inventory_db:6379
      restart: on-failure

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    depends_on:
      - account
      - catalog
      - order
    ports:
      - "8080:8080"
    environment:
      ACCOUNT_SERVICE_URL: account:8081
      CATALOG_SERVICE_URL: catalog:8082
      ORDER_SERVICE_URL: order:8083
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: viraj
      POSTGRES_USER: viraj
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      xpack.security.enabled: false
    restart: unless-stopped

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: viraj
      POSTGRES_USER: viraj
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  inventory_db:
    image: redis/redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
